# Change these first
owner: Delta-Core # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: VoIP
    url: voip.delta-core.app
  - name: Site Vitrine
    url: https://delta-core.fr
  - name: cPanel
    url: https://charlie.delta-core.fr
  - name: Plesk
    url: https://romain.delta-core.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.delta-core.fr
  # baseUrl: /your-repo-name
  logoUrl: https://delta-core.fr/assets/images/templates/navbar/logo-black.png
  name: Delta Core
  introTitle: "**Delta Core** est un hébergeur web qui vous propose des services web à prix réduits ! ."
  introMessage: Bienvenue sur le site de Status de Delta core où vous trouverez des données sur les performances du système et de nos maintenances.
  navbar:
    - title: Status
      href: /
    - title: Site Vitrine
      href: https://delta-core.fr

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
